version: '3.5'

services:
        redis:
            image: redis
        nginx:
          image: nginxwithconf
          ports:
            - 80:80

        frontend:
            image: frontend
            ports:
                - 5000:5000
            environment: 
                - API_URL=http://localhost:8000

        postgresdb:
            image: postgres
            restart: always
            environment: 
                - POSTGRES_PASSWORD=salasana
                - POSTGRES_USER=kayttaja
                - POSTGRES_DB=tietokantanimi  
            volumes:
                - ./database:/var/lib/postgresql/data

        backend:
            image: backend
            ports:
                - 8000:8000
            environment: 
                - FRONT_URL=http://localhost:5000
                - REDIS=redis
                - DB_PASSWORD=salasana
                - DB_USERNAME=kayttaja
                - DB_HOST=postgresdb
                - DB_NAME=tietokantanimi
        
        
        
